//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.19 at 09:35:22 PM EEST 
//


package org.opennms.ocs.inventory.client.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "checksum",
        "databaseid",
    "deviceid",
    "lastcome",
    "lastdate",
    "name",
    "tag"
})
@XmlRootElement(name = "COMPUTER")
public class Computer {

    @XmlElement(name = "DEVICEID", required = true)
    protected String deviceid;
    @XmlElement(name = "DATABASEID", required = true)
    protected String databaseid;
    @XmlElement(name = "CHECKSUM", required = true)
    protected String checksum;
    @XmlElement(name = "LASTCOME", required = true)
    protected String lastcome;
    @XmlElement(name = "LASTDATE", required = true)
    protected String lastdate;
    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "TAG", required = true)
    protected String tag;

    /**
     * Gets the value of the deviceid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEVICEID() {
        return deviceid;
    }

    /**
     * Sets the value of the deviceid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEVICEID(String value) {
        this.deviceid = value;
    }

    /**
     * Gets the value of the databaseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATABASEID() {
        return databaseid;
    }

    /**
     * Sets the value of the databaseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATABASEID(String value) {
        this.databaseid = value;
    }

    /**
     * Gets the value of the checksum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHECKSUM() {
        return checksum;
    }

    /**
     * Sets the value of the checksum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHECKSUM(String value) {
        this.checksum = value;
    }

    /**
     * Gets the value of the lastcome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTCOME() {
        return lastcome;
    }

    /**
     * Sets the value of the lastcome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTCOME(String value) {
        this.lastcome = value;
    }

    /**
     * Gets the value of the lastdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTDATE() {
        return lastdate;
    }

    /**
     * Sets the value of the lastdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTDATE(String value) {
        this.lastdate = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAG() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAG(String value) {
        this.tag = value;
    }

}
