//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.19 at 09:35:22 PM EEST 
//


package org.opennms.ocs.inventory.client.response;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)

@XmlRootElement(name = "COMPUTERS")
public class Computers {

    @XmlElement(name = "COMPUTER", required = true)
    private List<Computer> cmp;

    public List<Computer> getCmp() {
        return cmp;
    }

    public void setCmp(List<Computer> cmp) {
        this.cmp = cmp;
    }

}
